import { NextApiRequest, NextApiResponse } from 'next';
import { IGlobalMiningData } from '@/interfaces/real_time_data';

export default async function handler(
  request: NextApiRequest,
  response: NextApiResponse<IGlobalMiningData[]>
) {
  const globalMiningData: IGlobalMiningData[] = [
    { name: 'Afghanistan', countryCode: 'AFG', minedBlocks: 300 },
    { name: 'Angola', countryCode: 'AGO', minedBlocks: 100 },
    { name: 'Albania', countryCode: 'ALB', minedBlocks: 100 },
    { name: 'United Arab Emirates', countryCode: 'ARE', minedBlocks: 700 },
    { name: 'Argentina', countryCode: 'ARG', minedBlocks: 300 },
    { name: 'Armenia', countryCode: 'ARM', minedBlocks: 100 },
    { name: 'French Southern Territories', countryCode: 'ATF', minedBlocks: 100 },
    { name: 'Australia', countryCode: 'AUS', minedBlocks: 700 },
    { name: 'Austria', countryCode: 'AUT', minedBlocks: 700 },
    { name: 'Azerbaijan', countryCode: 'AZE', minedBlocks: 100 },
    { name: 'Burundi', countryCode: 'BDI', minedBlocks: 100 },
    { name: 'Belgium', countryCode: 'BEL', minedBlocks: 700 },
    { name: 'Benin', countryCode: 'BEN', minedBlocks: 100 },
    { name: 'Burkina Faso', countryCode: 'BFA', minedBlocks: 100 },
    { name: 'Bangladesh', countryCode: 'BGD', minedBlocks: 100 },
    { name: 'Bulgaria', countryCode: 'BGR', minedBlocks: 100 },
    { name: 'Bahamas', countryCode: 'BHS', minedBlocks: 100 },
    { name: 'Bosnia and Herzegovina', countryCode: 'BIH', minedBlocks: 300 },
    { name: 'Belarus', countryCode: 'BLR', minedBlocks: 300 },
    { name: 'Belize', countryCode: 'BLZ', minedBlocks: 100 },
    { name: 'Bolivia', countryCode: 'BOL', minedBlocks: 300 },
    { name: 'Brazil', countryCode: 'BRA', minedBlocks: 700 },
    { name: 'Brunei', countryCode: 'BRN', minedBlocks: 100 },
    { name: 'Bhutan', countryCode: 'BTN', minedBlocks: 100 },
    { name: 'Botswana', countryCode: 'BWA', minedBlocks: 100 },
    { name: 'Central African Republic', countryCode: 'CAF', minedBlocks: 100 },
    { name: 'Canada', countryCode: 'CAN', minedBlocks: 700 },
    { name: 'Switzerland', countryCode: 'CHE', minedBlocks: 700 },
    { name: 'Chile', countryCode: 'CHL', minedBlocks: 700 },
    { name: 'China', countryCode: 'CHN', minedBlocks: 900 },
    { name: "Cote d'Ivoire", countryCode: 'CIV', minedBlocks: 100 },
    { name: 'Cameroon', countryCode: 'CMR', minedBlocks: 100 },
    { name: 'Democratic Republic of Congo', countryCode: 'COD', minedBlocks: 100 },
    { name: 'Congo', countryCode: 'COG', minedBlocks: 400 },
    { name: 'Colombia', countryCode: 'COL', minedBlocks: 300 },
    { name: 'Costa Rica', countryCode: 'CRI', minedBlocks: 100 },
    { name: 'Cuba', countryCode: 'CUB', minedBlocks: 100 },
    { name: 'Cyprus', countryCode: 'CYP', minedBlocks: 100 },
    { name: 'Czechia', countryCode: 'CZE', minedBlocks: 300 },
    { name: 'Germany', countryCode: 'DEU', minedBlocks: 900 },
    { name: 'Djibouti', countryCode: 'DJI', minedBlocks: 100 },
    { name: 'Denmark', countryCode: 'DNK', minedBlocks: 100 },
    { name: 'Greenland', countryCode: 'GRL', minedBlocks: 100 },
    { name: 'Dominican Republic', countryCode: 'DOM', minedBlocks: 100 },
    { name: 'Algeria', countryCode: 'DZA', minedBlocks: 700 },
    { name: 'Ecuador', countryCode: 'ECU', minedBlocks: 400 },
    { name: 'Egypt', countryCode: 'EGY', minedBlocks: 300 },
    { name: 'Eritrea', countryCode: 'ERI', minedBlocks: 100 },
    { name: 'Spain', countryCode: 'ESP', minedBlocks: 900 },
    { name: 'Estonia', countryCode: 'EST', minedBlocks: 300 },
    { name: 'Ethiopia', countryCode: 'ETH', minedBlocks: 100 },
    { name: 'Finland', countryCode: 'FIN', minedBlocks: 100 },
    { name: 'Fiji', countryCode: 'FJI', minedBlocks: 100 },
    { name: 'France', countryCode: 'FRA', minedBlocks: 900 },
    { name: 'French Guiana', countryCode: 'GUF', minedBlocks: 100 },
    { name: 'Gabon', countryCode: 'GAB', minedBlocks: 100 },
    { name: 'United Kingdom', countryCode: 'GBR', minedBlocks: 100 },
    { name: 'Georgia', countryCode: 'GEO', minedBlocks: 100 },
    { name: 'Ghana', countryCode: 'GHA', minedBlocks: 100 },
    { name: 'Guinea', countryCode: 'GIN', minedBlocks: 300 },
    { name: 'Gambia', countryCode: 'GMB', minedBlocks: 100 },
    { name: 'Guinea-Bissau', countryCode: 'GNB', minedBlocks: 100 },
    { name: 'Equatorial Guinea', countryCode: 'GNQ', minedBlocks: 100 },
    { name: 'Greece', countryCode: 'GRC', minedBlocks: 700 },
    { name: 'Guatemala', countryCode: 'GTM', minedBlocks: 100 },
    { name: 'Guyana', countryCode: 'GUY', minedBlocks: 100 },
    { name: 'Honduras', countryCode: 'HND', minedBlocks: 100 },
    { name: 'Croatia', countryCode: 'HRV', minedBlocks: 300 },
    { name: 'Haiti', countryCode: 'HTI', minedBlocks: 100 },
    { name: 'Hungary', countryCode: 'HUN', minedBlocks: 300 },
    { name: 'Indonesia', countryCode: 'IDN', minedBlocks: 300 },
    { name: 'India', countryCode: 'IND', minedBlocks: 700 },
    { name: 'Ireland', countryCode: 'IRL', minedBlocks: 700 },
    { name: 'Iran', countryCode: 'IRN', minedBlocks: 900 },
    { name: 'Iraq', countryCode: 'IRQ', minedBlocks: 700 },
    { name: 'Iceland', countryCode: 'ISL', minedBlocks: 700 },
    { name: 'Israel', countryCode: 'ISR', minedBlocks: 100 },
    { name: 'Italy', countryCode: 'ITA', minedBlocks: 900 },
    { name: 'Jamaica', countryCode: 'JAM', minedBlocks: 100 },
    { name: 'Jordan', countryCode: 'JOR', minedBlocks: 100 },
    { name: 'Japan', countryCode: 'JPN', minedBlocks: 700 },
    { name: 'Kazakhstan', countryCode: 'KAZ', minedBlocks: 100 },
    { name: 'Kenya', countryCode: 'KEN', minedBlocks: 100 },
    { name: 'Kyrgyzstan', countryCode: 'KGZ', minedBlocks: 100 },
    { name: 'Cambodia', countryCode: 'KHM', minedBlocks: 100 },
    { name: 'South Korea', countryCode: 'KOR', minedBlocks: 100 },
    { name: 'Kosovo', countryCode: 'XXK', minedBlocks: 100 },
    { name: 'Kuwait', countryCode: 'KWT', minedBlocks: 100 },
    { name: 'Laos', countryCode: 'LAO', minedBlocks: 100 },
    { name: 'Lebanon', countryCode: 'LBN', minedBlocks: 100 },
    { name: 'Liberia', countryCode: 'LBR', minedBlocks: 100 },
    { name: 'Libya', countryCode: 'LBY', minedBlocks: 300 },
    { name: 'Sri Lanka', countryCode: 'LKA', minedBlocks: 100 },
    { name: 'Lesotho', countryCode: 'LSO', minedBlocks: 100 },
    { name: 'Lithuania', countryCode: 'LTU', minedBlocks: 300 },
    { name: 'Luxembourg', countryCode: 'LUX', minedBlocks: 100 },
    { name: 'Latvia', countryCode: 'LVA', minedBlocks: 300 },
    { name: 'Morocco', countryCode: 'MAR', minedBlocks: 100 },
    { name: 'Moldova', countryCode: 'MDA', minedBlocks: 300 },
    { name: 'Madagascar', countryCode: 'MDG', minedBlocks: 100 },
    { name: 'Mexico', countryCode: 'MEX', minedBlocks: 300 },
    { name: 'North Macedonia', countryCode: 'MKD', minedBlocks: 100 },
    { name: 'Mali', countryCode: 'MLI', minedBlocks: 100 },
    { name: 'Myanmar', countryCode: 'MMR', minedBlocks: 700 },
    { name: 'Montenegro', countryCode: 'MNE', minedBlocks: 100 },
    { name: 'Mongolia', countryCode: 'MNG', minedBlocks: 100 },
    { name: 'Mozambique', countryCode: 'MOZ', minedBlocks: 100 },
    { name: 'Mauritania', countryCode: 'MRT', minedBlocks: 100 },
    { name: 'Malawi', countryCode: 'MWI', minedBlocks: 100 },
    { name: 'Malaysia', countryCode: 'MYS', minedBlocks: 700 },
    { name: 'Namibia', countryCode: 'NAM', minedBlocks: 100 },
    { name: 'New Caledonia', countryCode: 'NCL', minedBlocks: 100 },
    { name: 'Niger', countryCode: 'NER', minedBlocks: 100 },
    { name: 'Nigeria', countryCode: 'NGA', minedBlocks: 300 },
    { name: 'Nicaragua', countryCode: 'NIC', minedBlocks: 100 },
    { name: 'Netherlands', countryCode: 'NLD', minedBlocks: 700 },
    { name: 'Norway', countryCode: 'NOR', minedBlocks: 700 },
    { name: 'Nepal', countryCode: 'NPL', minedBlocks: 100 },
    { name: 'New Zealand', countryCode: 'NZL', minedBlocks: 300 },
    { name: 'Oman', countryCode: 'OMN', minedBlocks: 700 },
    { name: 'Pakistan', countryCode: 'PAK', minedBlocks: 300 },
    { name: 'Panama', countryCode: 'PAN', minedBlocks: 100 },
    { name: 'Peru', countryCode: 'PER', minedBlocks: 300 },
    { name: 'Philippines', countryCode: 'PHL', minedBlocks: 100 },
    { name: 'Papua New Guinea', countryCode: 'PNG', minedBlocks: 100 },
    { name: 'Poland', countryCode: 'POL', minedBlocks: 300 },
    { name: 'Puerto Rico', countryCode: 'PRI', minedBlocks: 100 },
    { name: 'North Korea', countryCode: 'PRK', minedBlocks: 100 },
    { name: 'Portugal', countryCode: 'PRT', minedBlocks: 700 },
    { name: 'Paraguay', countryCode: 'PRY', minedBlocks: 100 },
    { name: 'Qatar', countryCode: 'QAT', minedBlocks: 700 },
    { name: 'Romania', countryCode: 'ROU', minedBlocks: 300 },
    { name: 'Russia', countryCode: 'RUS', minedBlocks: 700 },
    { name: 'Rwanda', countryCode: 'RWA', minedBlocks: 100 },
    { name: 'Western Sahara', countryCode: 'ESH', minedBlocks: 100 },
    { name: 'Saudi Arabia', countryCode: 'SAU', minedBlocks: 700 },
    { name: 'Sudan', countryCode: 'SDN', minedBlocks: 100 },
    { name: 'South Sudan', countryCode: 'SSD', minedBlocks: 100 },
    { name: 'Senegal', countryCode: 'SEN', minedBlocks: 300 },
    { name: 'Solomon Islands', countryCode: 'SLB', minedBlocks: 100 },
    { name: 'Sierra Leone', countryCode: 'SLE', minedBlocks: 100 },
    { name: 'El Salvador', countryCode: 'SLV', minedBlocks: 100 },
    { name: 'Somalia', countryCode: 'SOM', minedBlocks: 100 },
    { name: 'Serbia', countryCode: 'SRB', minedBlocks: 300 },
    { name: 'Suriname', countryCode: 'SUR', minedBlocks: 100 },
    { name: 'Slovakia', countryCode: 'SVK', minedBlocks: 300 },
    { name: 'Slovenia', countryCode: 'SVN', minedBlocks: 300 },
    { name: 'Sweden', countryCode: 'SWE', minedBlocks: 700 },
    { name: 'Eswatini', countryCode: 'SWZ', minedBlocks: 100 },
    { name: 'Syria', countryCode: 'SYR', minedBlocks: 100 },
    { name: 'Chad', countryCode: 'TCD', minedBlocks: 100 },
    { name: 'Togo', countryCode: 'TGO', minedBlocks: 100 },
    { name: 'Thailand', countryCode: 'THA', minedBlocks: 700 },
    { name: 'Tajikistan', countryCode: 'TJK', minedBlocks: 100 },
    { name: 'Turkmenistan', countryCode: 'TKM', minedBlocks: 100 },
    { name: 'Timor', countryCode: 'TLS', minedBlocks: 100 },
    { name: 'Trinidad and Tobago', countryCode: 'TTO', minedBlocks: 100 },
    { name: 'Tunisia', countryCode: 'TUN', minedBlocks: 100 },
    { name: 'Turkey', countryCode: 'TUR', minedBlocks: 100 },
    { name: 'Taiwan', countryCode: 'TWN', minedBlocks: 100 },
    { name: 'Tanzania', countryCode: 'TZA', minedBlocks: 100 },
    { name: 'Uganda', countryCode: 'UGA', minedBlocks: 100 },
    { name: 'Ukraine', countryCode: 'UKR', minedBlocks: 300 },
    { name: 'Uruguay', countryCode: 'URY', minedBlocks: 100 },
    { name: 'United States', countryCode: 'USA', minedBlocks: 900 },
    { name: 'Uzbekistan', countryCode: 'UZB', minedBlocks: 100 },
    { name: 'Venezuela', countryCode: 'VEN', minedBlocks: 100 },
    { name: 'Vietnam', countryCode: 'VNM', minedBlocks: 300 },
    { name: 'Vanuatu', countryCode: 'VUT', minedBlocks: 100 },
    { name: 'West Bank', countryCode: 'PSX', minedBlocks: 100 },
    { name: 'Yemen', countryCode: 'YEM', minedBlocks: 100 },
    { name: 'South Africa', countryCode: 'ZAF', minedBlocks: 100 },
    { name: 'Zambia', countryCode: 'ZMB', minedBlocks: 100 },
    { name: 'Zimbabwe', countryCode: 'ZWE', minedBlocks: 100 },
    { name: 'Cape Verde', countryCode: 'CPV', minedBlocks: 100 },
    { name: 'Comoros', countryCode: 'COM', minedBlocks: 100 },
    { name: 'Mauritius', countryCode: 'MUS', minedBlocks: 100 },
    { name: 'Seychelles', countryCode: 'SYC', minedBlocks: 100 },
    { name: 'Bahrain', countryCode: 'BHR', minedBlocks: 100 },
    { name: 'Maldives', countryCode: 'MDV', minedBlocks: 100 },
    { name: 'Marshall Islands', countryCode: 'MHL', minedBlocks: 100 },
    { name: 'Micronesia (country)', countryCode: 'FSM', minedBlocks: 100 },
    { name: 'Nauru', countryCode: 'NRU', minedBlocks: 100 },
    { name: 'Palau', countryCode: 'PLW', minedBlocks: 100 },
    { name: 'Samoa', countryCode: 'WSM', minedBlocks: 100 },
    { name: 'Singapore', countryCode: 'SGP', minedBlocks: 100 },
    { name: 'Tonga', countryCode: 'TON', minedBlocks: 100 },
    { name: 'Tuvalu', countryCode: 'TUV', minedBlocks: 100 },
    { name: 'Antigua and Barbuda', countryCode: 'ATG', minedBlocks: 100 },
    { name: 'Barbados', countryCode: 'BRB', minedBlocks: 100 },
    { name: 'Dominica', countryCode: 'DMA', minedBlocks: 100 },
    { name: 'Grenada', countryCode: 'GRD', minedBlocks: 100 },
    { name: 'Saint Kitts and Nevis', countryCode: 'KNA', minedBlocks: 100 },
    { name: 'Saint Lucia', countryCode: 'LCA', minedBlocks: 100 },
    { name: 'Saint Vincent and the Grenadines', countryCode: 'VCT', minedBlocks: 100 },
    { name: 'Andorra', countryCode: 'AND', minedBlocks: 100 },
    { name: 'Liechtenstein', countryCode: 'LIE', minedBlocks: 100 },
    { name: 'Malta', countryCode: 'MLT', minedBlocks: 100 },
    { name: 'Monaco', countryCode: 'MCO', minedBlocks: 100 },
    { name: 'San Marino', countryCode: 'SMR', minedBlocks: 100 },
    { name: 'Kiribati', countryCode: 'KIR', minedBlocks: 100 },
    { name: 'Sao Tome and Principe', countryCode: 'STP', minedBlocks: 100 },
  ];

  if (request.method === 'GET') {
    response.status(200).json(globalMiningData);
  }
}
